[package]
name = "bitonic-sorter"
version = "0.1.0"
authors = ["hhiroki <gyouzakuuka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ex) cargo add rand
rand = "0.7.3"
rand_pcg = "0.2.1"
